config/routes.rb
Rails.application.routes.draw do
  resources :talents

end

app/models/talent.rb
class Talent < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/talents_controller.rb
class TalentsController < ApplicationController
  before_action :set_talent, only: [:show, :edit, :update, :destroy]

  # GET /talents
  # GET /talents.json
  def index
    @talents = Talent.all
  end

  # GET /talents/1
  # GET /talents/1.json
  def show
  end

  # GET /talents/new
  def new
    @talent = Talent.new
  end

  # GET /talents/1/edit
  def edit
  end

  # POST /talents
  # POST /talents.json
  def create
    @talent = Talent.new(talent_params)

    respond_to do |format|
      if @talent.save
        format.html { redirect_to @talent, notice: 'Talent was successfully created.' }
        format.json { render :show, status: :created, location: @talent }
      else
        format.html { render :new }
        format.json { render json: @talent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /talents/1
  # PATCH/PUT /talents/1.json
  def update
    respond_to do |format|
      if @talent.update(talent_params)
        format.html { redirect_to @talent, notice: 'Talent was successfully updated.' }
        format.json { render :show, status: :ok, location: @talent }
      else
        format.html { render :edit }
        format.json { render json: @talent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talents/1
  # DELETE /talents/1.json
  def destroy
    @talent.destroy
    respond_to do |format|
      format.html { redirect_to talents_url, notice: 'Talent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_talent
      @talent = Talent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def talent_params
      params.require(:talent).permit(:First, :Last, :Talent, :Description, :done)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/talents_helper.rb
module TalentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TALENTS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/talents/_form.html.erb
<%= form_for(@talent) do |f| %>
  <% if @talent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@talent.errors.count, "error") %> prohibited this talent from being saved:</h2>

      <ul>
      <% @talent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :First %><br>
    <%= f.text_field :First %>
  </div>
  <div class="field">
    <%= f.label :Last %><br>
    <%= f.text_field :Last %>
  </div>
  <div class="field">
    <%= f.label :Talent %><br>
    <%= f.text_field :Talent %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :Description %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/talents/edit.html.erb
<h1>Editing Talent</h1>

<%= render 'form' %>

<%= link_to 'Show', @talent %> |
<%= link_to 'Back', talents_path %>

app/views/talents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Talents</h1>

<table>
  <thead>
    <tr>
      <th>First</th>
      <th>Last</th>
      <th>Talent</th>
      <th>Description</th>
      <th>Done</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li class="active"><a href="#">About</a></li>
        <li class="active"><a href="#">Contact</a></li>
        <li class="active"><a href="#">Registr</a></li>
        <li class="active"><a href="#">Login</a></li>
      </ul>
    </div>
  </div>
</nav>
    <% @talents.each do |talent| %>
      <tr>
        <td><%= talent.First %></td>
        <td><%= talent.Last %></td>
        <td><%= talent.Talent %></td>
        <td><%= talent.Description %></td>
        <td><%= talent.done %></td>
        <td><%= link_to 'Show', talent %></td>
        <td><%= link_to 'Edit', edit_talent_path(talent) %></td>
        <td><%= link_to 'Destroy', talent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Talent', new_talent_path %>

app/views/talents/new.html.erb
<h1>New Talent</h1>

<%= render 'form' %>

<%= link_to 'Back', talents_path %>

app/views/talents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First:</strong>
  <%= @talent.First %>
</p>

<p>
  <strong>Last:</strong>
  <%= @talent.Last %>
</p>

<p>
  <strong>Talent:</strong>
  <%= @talent.Talent %>
</p>

<p>
  <strong>Description:</strong>
  <%= @talent.Description %>
</p>

<p>
  <strong>Done:</strong>
  <%= @talent.done %>
</p>

<%= link_to 'Edit', edit_talent_path(@talent) %> |
<%= link_to 'Back', talents_path %>